# Generated by Django 3.0.6 on 2020-05-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_auto_20200515_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='lemonade',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.ManyToManyField(to='Sales.LemonadeSet')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales.Order'),
        ),
    ]
